version: "3"
services:
  base:
    build:
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    env_file: .env
    networks:
      - internal_net
