version: "3"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./rabbitmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./rabbitmq/definitions.json
        target: /definitions.json
    ports:
      - 15672:15672
    networks:
      - internal_net

  input:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 1_input
    networks:
      - outside_net
      - internal_net
    depends_on:
      parsers:
        condition: service_healthy

  parsers:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 2_parsers
    deploy:
      mode: replicated
      replicas: ${PARSERS_SCALE}
    depends_on:
      joiners:
        condition: service_healthy

  joiners:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 3_joiners
    deploy:
      mode: replicated
      replicas: ${JOINERS_SCALE}
    depends_on:
      rain_aggregators:
        condition: service_healthy

  rain_aggregators:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 4_1_rain_aggregators
    deploy:
      mode: replicated
      replicas: ${RAIN_AGGREGATORS_SCALE}
    depends_on:
      rabbitmq:
        condition: service_healthy

  rain_reducer:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 5_1_rain_reducer
    depends_on:
      rabbitmq:
        condition: service_healthy

  output:
    extends:
      file: compose-base-service.yaml
      service: base
    build:
      args:
        WORKDIR: 6_output
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    build:
      dockerfile: Dockerfile
      args:
        WORKDIR: client
    volumes:
      - type: bind
        source: ./client/data
        target: /tmp/data
      - type: bind
        source: config.ini
        target: /config.ini
    networks:
      - outside_net
    depends_on:
      - input

networks:
  outside_net:
    ipam:
      driver: default
  internal_net:
    ipam:
      driver: default
