version: "3"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./rabbitmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    ports:
      - 15672:15672
    networks:
      - internal_net

  input:
    build:
      dockerfile: Dockerfile
      args:
        WORKDIR: input
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    networks:
      - outside_net
      - internal_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  parsers:
    build:
      dockerfile: Dockerfile
      args:
        WORKDIR: parsers
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - type: bind
        source: config.ini
        target: /config.ini
    networks:
      - internal_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    build:
      dockerfile: Dockerfile
      args:
        WORKDIR: client
    volumes:
      - type: bind
        source: ./client/data
        target: /tmp/data
      - type: bind
        source: config.ini
        target: /config.ini
    networks:
      - outside_net
    depends_on:
      - input

networks:
  outside_net:
    ipam:
      driver: default
  internal_net:
    ipam:
      driver: default
